name: Deploy to test site

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

env:
  DOTNET_VERSION: '7.x' # The .NET SDK version to use

inputs:
    name:
        description: 'Artifact name'
        required: false
        default: 'artifact'
    path:
        description: "Path of the directory containing the static assets."
        required: true
        default: "src/"

jobs:
  build:
    environment: Testing
    name: Deploy to test site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore NuGet dependencies
      run: dotnet restore

    - name: Build
      run: dotnet run --urls "http://localhost:5048" --project ./src/ --configuration Release -- static-only
    
    - name: Archive artifact
      shell: sh
      if: runner.os == 'Linux'
      run: |
        chmod -c -R +rX "$GITHUB_WORKSPACE" |
        while read line; do
           echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
        tar \
          --dereference --hard-dereference \
          --directory "$GITHUB_WORKSPACE/src/StaticWebSite" \
          -cvf "$GITHUB_WORKSPACE/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v3
    
    - name: Upload Github Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: ${{ inputs.name }}
        path: ${{ GITHUB_WORKSPACE }}/artifact.tar
        if-no-files-found: error
    
    - name: Deploy artifact
      uses: actions/deploy-pages@v1
