# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 部署到生产站点

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 克隆存储库
      uses: actions/checkout@v4
    - name: 登陆到 Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 预处理-移除不需要的组件
      run: dotnet run --configuration Release --project ./src/AnEoT.Vintage.Tool/AnEoT.Vintage.Tool.csproj remove-unnecessary-component --webroot-path ${{ github.workspace }}/src/AnEoT.Vintage/wwwroot
    - name: 构建主项目及生成静态网页
      run: dotnet run --configuration Release --project ./src/AnEoT.Vintage/AnEoT.Vintage.csproj -- static-only --ConvertWebP true --urls "http://localhost:5048" --RssBaseUri "https://aneot-vintage.baka632.com/" --RssIncludeAllArticles true --RssAddCssStyle true
    - name: 上传生成的静态网页
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name aneotvintage --auth-mode key --overwrite -d '$web' -s ./src/AnEoT.Vintage/StaticWebSite
    - name: 登出 Azure
      run: |
            az logout
      if: always()