# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to production site

on:
  push:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 预处理-移除不需要的组件
      run: dotnet run --configuration Release --project ./src/AnEoT.Vintage.Tool/AnEoT.Vintage.Tool.csproj remove-unnecessary-component --webroot-path ${{ github.workspace }}/src/AnEoT.Vintage/wwwroot
    - name: 构建主项目及生成静态网页
      run: dotnet run --configuration Release --project ./src/AnEoT.Vintage/AnEoT.Vintage.csproj -- static-only --ConvertWebP true --urls "http://localhost:5048"
    - name: 后期处理-修复 GitHub Pages 环境的导航栏
      run: dotnet run --configuration Release --project ./src/AnEoT.Vintage.Tool/AnEoT.Vintage.Tool.csproj fix-navbar --static-content-path ${{ github.workspace }}/src/AnEoT.Vintage/StaticWebSite
    - name: 配置 GitHub Pages
      uses: actions/configure-pages@v3
    - name: 上传生成的静态网页
      uses: actions/upload-pages-artifact@v2
      with:
        path: './src/AnEoT.Vintage/StaticWebSite'
    - name: 将静态网页部署到 GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
